#!/bin/bash
ARGC=$#
echo "ARGS = $ARGC"
set -e
sudo make clean
sudo rm -f /etc/php/8.4/cli/conf.d/25-wccz.ini
clear
b=0
if [ $ARGC -eq $b ]; then
  rm -f ./stub/*_arginfo.h
  FILES=./stub/*.stub.php
  for f in $FILES
  do
    target="${f/.stub.php/_arginfo.h}"
    make $target
  done
fi

sudo make install
