#!/bin/bash
set -e
sudo make clean
clear

#make ./stub/toml_arginfo.h

#make ./stub/irow_arginfo.h
#make ./stub/iconfig_arginfo.h
#make ./stub/ds_arginfo.h
#make ./stub/db_arginfo.h
#make ./stub/model_arginfo.h
#make ./stub/operations_arginfo.h
#make sqlipart_arginfo.h
#make toml_arginfo.h
#make htmlgem_arginfo.h
#make wcc_config_arginfo.h
#make request_globals_arginfo.h
#make global_response_arginfo.h
#make filter_wcf_arginfo.h
#make ustr8_arginfo.h

sudo make install
