#!/bin/bash
set -e
./stop.sh
pushd src 
./buildme
popd
pushd cpp-zpp
./buildme
popd
pushd wcc-zero
./buildme
popd
pushd wcc-routes
./buildme
popd
pushd wcc-html
./buildme
popd
pushd wcc-more
./buildme
popd
pushd wcc-database
./buildme
popd
./start.sh
echo "DONE"
