#!/bin/bash
./stop.sh
pushd php_zpp 
phpize
./configure
popd
pushd wcc-zero
phpize
./configure
popd
pushd wcc-routes
phpize
./configure
popd
pushd wcc-html
phpize
./configure
popd
pushd wcc-more
phpize
./configure
popd
pushd wcc-database
phpize
./configure
popd
./start.sh
echo "DONE PHPIZE"
