-- Not easy to create, extra keywords in isql
-- CREATE DATABASE 'localhost:/path' USER 'FBUSER' password 'y0ghurt+'
-- CREATE DATABASE '/var/lib/firebird/3.0/test.db' user SYSDBA password 'xxx';
--
create table "test" (
  "id" integer generated by default as identity primary key,
  "name" varchar(1024) not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null
);

create table "test2" (
  "id" integer generated by default as identity primary key,
  "test_id" integer not null,
  "value" varchar(255) not null
);

CREATE TABLE "test_intermediate" (
  "test_id" int NOT NULL,
  "test_related_id" int NOT NULL,
  "intermediate_value" varchar(1024) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("test_id","test_related_id")
);

CREATE TABLE "test_related" (
  "id" integer generated by default as identity PRIMARY KEY,
  "value" varchar(1024) NOT NULL,
  "created_at" timestamp  DEFAULT NULL,
  "updated_at" timestamp  DEFAULT NULL
);

CREATE TABLE "author" (
	"author_id" integer generated by default as identity PRIMARY KEY,
	"parent_author_id" integer,
	"publisher_id" integer,
	"name" VARCHAR(25) DEFAULT 'default_name' NOT NULL,
	"updated_at" timestamp,
	"created_at" timestamp,
	"some_Date" date,
	"some_time" time,
	"some_text" BLOB SUB_TYPE TEXT,
	"encrypted_password" varchar(50),
	"mixedCaseField" varchar(50)
);

CREATE TABLE "book" (
	"book_id" integer generated by default as identity PRIMARY KEY,
	"author_id" integer,
	"secondary_author_id" integer,
	"name" VARCHAR(50),
	"numeric_test" VARCHAR(10) DEFAULT '0',
	"special" NUMERIC(10,2) DEFAULT 0.0
);

CREATE TABLE "publisher" (
	"publisher_id" integer generated by default as identity PRIMARY KEY,
	"name" VARCHAR(25) DEFAULT 'default_name'  NOT NULL 
);

CREATE TABLE "venue" (
	"id" integer generated by default as identity PRIMARY KEY,
	"name" varchar(50),
	"city" varchar(60),
	"state" char(2),
	"address" varchar(50),
	"phone" varchar(10) default NULL,
	UNIQUE("name","address")
);

CREATE TABLE "event" (
	"id" integer generated by default as identity PRIMARY KEY,
	"venue_id" integer,
	"host_id" integer NOT NULL,
	"title" varchar(60) NOT NULL,
	"description" varchar(10),
	"type" varchar(15) default NULL
);

CREATE TABLE "host" (
	"id" integer generated by default as identity PRIMARY KEY,
	"name" VARCHAR(25)
);

CREATE TABLE "employee" (
	"id" integer generated by default as identity PRIMARY KEY,
	"first_name" VARCHAR(255) NOT NULL,
	"last_name" VARCHAR(255) NOT NULL,
	"nick_name" VARCHAR(255) NOT NULL
);

CREATE TABLE "position" (
	"id" integer generated by default as identity PRIMARY KEY,
	"employee_id" integer NOT NULL,
	"title" VARCHAR(255) NOT NULL,
	"active" SMALLINT NOT NULL
);

CREATE TABLE "rm-bldg" (
    "rm-id" integer generated by default as identity PRIMARY KEY,
    "rm-name" VARCHAR(10) NOT NULL,
    "space out" VARCHAR(1) NOT NULL
);

CREATE TABLE "awesome_people" (
	"id" integer generated by default as identity primary key,
	"author_id" integer,
	"is_awesome" integer default 1
);

CREATE TABLE "amenity" (
	"amenity_id" integer generated by default as identity primary key,
	"type" varchar(40) NOT NULL
);

CREATE TABLE "property" (
	"property_id" integer generated by default as identity primary key
);

CREATE TABLE "property_amenity" (
	"id" integer generated by default as identity primary key,
	"amenity_id" integer not null,
	"property_id" integer not null
);

CREATE TABLE "user" (
	"id" integer generated by default as identity primary key
);

CREATE TABLE "newsletter" (
	"id" integer generated by default as identity primary key
);

CREATE TABLE "user_newsletter" (
  "id" integer generated by default as identity primary key,
  "user_id" integer not null,
  "newsletter_id" integer not null
);

CREATE TABLE "valuestore" (
  "id" integer generated by default as identity primary key,
  "key" varchar(20) DEFAULT '' NOT NULL ,
  "value" varchar(255) DEFAULT ''  NOT NULL 
);

-- reproduces issue GH-96 for testing
CREATE INDEX "id_and_user_id_idx" ON "user_newsletter" ("id", "user_id");


CREATE TABLE  "payment" (
  "id" integer generated by default as identity primary key,
  "memberid" integer not null,
  "emailid" integer not null,
  "status" varchar(15) not null,
  "total_cost" integer not null,
  "trans_fee" integer not null,
  "trans_code" varchar(80) not null,
  "created_at" timestamp not null
);

-- --------------------------------------------------------

--
-- Table structure for table pay_item
--

CREATE TABLE  "pay_item" (
  "trans_id" integer not null,
  "id" integer not null,
  "detail" varchar(255) default null,
  "amount" integer not null,
  "purpose" varchar(15) not null,
  PRIMARY KEY ("trans_id","id")
);