#!/bin/bash
ARGC=$#
export XDEBUG_MODE=off
echo "ARGS = $ARGC"
set -e
sudo make clean
clear
b=0
if [ $ARGC -eq $b ]; then
  rm -f ./stub/*_arginfo.h
  FILES=./stub/*.stub.php
  for f in $FILES
  do
    target="${f/.stub.php/_arginfo.h}"
    echo $target
    make $target
  done
fi
# not making combined extension right now
#sudo make install
#sudo cp zpp.ini $pconf/zpp.ini
